// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, fs, http, path, server;

  express = require('express');

  app = express();

  http = require('http');

  path = require('path');

  fs = require('fs');

  app.set('port', process.env.PORT);


  /*================================================================================================
  Routs
  ================================================================================================
   */


  /*
  app.get '/', (req, res)  ->  
    console.log "requesting series homepage"
    res.redirect '/index.html'
    return
   */

  console.log("Attempting to start server at " + (app.get('port')));

  server = http.createServer(app).listen(app.get('port'), function() {
    var address, powFile, powHost;
    address = server.address();
    console.log("Node app is running at ", address);
    if (process.platform === 'darwin') {
      powHost = "windows.tvseries";
      powFile = path.resolve(process.env['HOME'], ".pow/" + powHost);
      fs.writeFile(powFile, address.port, (function(_this) {
        return function(err) {
          var unhost;
          if (err) {
            return console.error(err);
          }
          console.log("Hosted on: " + powHost + ".dev");
          unhost = function() {
            var e;
            try {
              fs.unlinkSync(powFile);
              console.log("Unhosted from: " + powHost + ".dev");
            } catch (_error) {
              e = _error;
              if (err) {
                return console.error(err);
              }
            }
          };
          process.on('SIGINT', function() {
            unhost();
            process.exit();
          });
          return process.on('exit', function(code) {
            unhost();
          });
        };
      })(this));
    }
  });

  app.use(express["static"](__dirname + '/public'));

}).call(this);


//# sourceMappingURL=index.js.map
